### ISSUE TITLE
docker: invalid reference format.

### ISSUE THREAD

**Issue by aminmiri** [georgettica/kubernetes-bookmark-bar#7]
When I run the ./run.sh I got this error: 
`docker: invalid reference format.
See 'docker run --help'.`

**Comment by aminmiri** [comment]
Dont know why but issue fixed after I remove   ` "${ADDITIONAL_CONTAINER_ENGINE_ARGS}" \` given that it's value was empty.

**Comment by georgettica** [comment]
I am not sure, what is your setup?
Maybe there is an underlying issue we can fix here

**Comment by aminmiri** [comment]
@georgettica  I'm using `Docker version 20.10.5, build 55c4c88`
The OS is `Ubuntu 18.04.1`
I fixed this issue by removing the `{ }` form the variables and just call them using `$`. So for example instead of using :
`${CONTAINER_ENGINE} run \
    --rm \
    --interactive \
    --tty \
    --volume \
        "$(pwd)":${CONTAINER_BASE_DIR}/data \
    "${ADDITIONAL_CONTAINER_ENGINE_ARGS}" \
    "${IMG}" \
    python3 \
    	bookmark_generator.py \
	data/bookmark.yaml > "${OUTPUT_HTML_FILE}"`

I use this one:
`$CONTAINER_ENGINE run \
    --rm \
    --interactive \
    --tty \
    --volume \
    "$(pwd)":$CONTAINER_BASE_DIR/data \
    $ADDITIONAL_CONTAINER_ENGINE_ARGS \
    "${IMG}" \
    python3 \
    bookmark_generator.py \
    data/bookmark.yaml > "${OUTPUT_HTML_FILE}"`

**Comment by georgettica** [comment]
And keeping them in double quotes still works

And as discussed, this refers to #10

**Comment by georgettica** [comment]
I merged and I'll test it maybe later with a container with ubuntu to see if I missed something
