### ISSUE TITLE
sample.yaml not fount 

### ISSUE THREAD

**Issue by aminmiri** [georgettica/kubernetes-bookmark-bar#8]
Line 21 in run.sh should specify the correct name of the yaml file.
So instead of `data/sample.yaml > "${OUTPUT_HTML_FILE}"`
It should be `data/bookmark.yaml > "${OUTPUT_HTML_FILE}"`

**Comment by georgettica** [comment]
Looks like a good catch!
If this is tested and has a works with the fix add a PR and I'll happily merge it.

(I am using the github action to build the html so I guess I missed it)

**Comment by georgettica** [comment]
Yup, it's I consistent
https://github.com/georgettica/kubernetes-bookmark-bar/blob/d99cc25c8083dde88c9c9628b516d465ac94be9e/.github/workflows/upload-bookmark-html.yml#L32

**Comment by aminmiri** [comment]
@georgettica  It looks like I have no permissions to create a PR, therefore, the only thing need to be change to fix this issue is the last line in run.sh file. 
It should be like this:
`data/bookmark.yaml > "${OUTPUT_HTML_FILE}"`

**Comment by georgettica** [comment]
Was related to #9
